[theme]
base = "dark"
primaryColor = "#388bfd"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6f1ff"

[server]
maxUploadSize = 200
enableCORS = false

[browser]
gatherUsageStats = false
